name = "Theseus S2"
author = "Explosivejoe, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a191f7e645452689e59d53463c97133c2fdcc499273c7c72240ef5429dde820"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
