name = "Theseus S2"
author = "Explosivejoe, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff454287af6797bfd05c0638dbdac90cc1d4b601f3ec5181cd95b8cf700d865d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
