name = "Theseus S2"
author = "Explosivejoe, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6454484a0b7fdf74b208ee8e9ddc9404510f90f72c8ba993a7b6b46b8c196942"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
